// Argent77

// Specialized ALTER_SPELL_EFFECT: Updates primary parameters based on matching opcode and resource
DEFINE_PATCH_FUNCTION ALTER_SPELL_EFFECT_RESREF
INT_VAR
  header          = 0   // 0 = all headers
  match_opcode    = "-1"
  opcode          = "-1"
  parameter1      = "-1"
  parameter2      = "-1"
STR_VAR
  match_resource  = ~~
  resource        = ~~
BEGIN
  READ_ASCII 0 sig (8)
  PATCH_IF (~%sig%~ STR_EQ ~SPL V1  ~) BEGIN
    SET header -= 1
    READ_LONG 0x64 ofs_abils
    READ_SHORT 0x68 num_abils
    READ_LONG 0x6a ofs_effects
    FOR (abil = 0; abil < num_abils; ++abil) BEGIN
      SET ofs_abil = ofs_abils + abil * 0x28
      PATCH_IF (header < 0 || header = abil) BEGIN
        READ_SHORT (ofs_abil + 0x1e) num_effects
        READ_SHORT (ofs_abil + 0x20) idx_effects
        FOR (fx = 0; fx < num_effects; ++fx) BEGIN
          SET ofs_fx = ofs_effects + (idx_effects + fx) * 0x30
          READ_SHORT (ofs_fx + 0x00) op
          READ_ASCII (ofs_fx + 0x14) res (8) NULL
          PATCH_IF ((match_opcode = "-1" || op = match_opcode) && ~%res%~ STR_EQ ~%match_resource%~) BEGIN
            PATCH_IF (opcode != "-1") BEGIN WRITE_SHORT (ofs_fx + 0x00) opcode END
            PATCH_IF (parameter1 != "-1") BEGIN WRITE_LONG (ofs_fx + 0x04) parameter1 END
            PATCH_IF (parameter2 != "-1") BEGIN WRITE_LONG (ofs_fx + 0x08) parameter2 END
            WRITE_ASCIIE (ofs_fx + 0x14) ~%resource%~ (8)
          END
        END
      END
    END
  END ELSE BEGIN
    PATCH_WARN ~Not a valid SPL resource. Skipping operation.~
  END
END


DEFINE_ACTION_FUNCTION UPDATE_EPILOG_PORTRAIT
STR_VAR
  match_portrait = ~~ // original portrait BMP resref as regexp
  portrait = ~~
BEGIN
  COPY_EXISTING_REGEXP ~^.+\.2da$~ ~override~
    COUNT_2DA_ROWS 1 numRows
    PATCH_IF (numRows > 2) BEGIN
      READ_2DA_ENTRY 1 0 1 value
      PATCH_IF (~%value%~ STRING_MATCHES_REGEXP ~\*%match_portrait%~ = 0) BEGIN
        SET_2DA_ENTRY 1 0 1 ~*%portrait%~
      END
    END
  BUT_ONLY
END

DEFINE_ACTION_FUNCTION CHANGE_NPC_PORTRAIT
  STR_VAR
    portrait = ""
    source_dir = ""
    cre_file_1 = ""
    cre_file_2 = ""
    cre_file_3 = ""
    cre_file_4 = ""
    cre_file_5 = ""
    cre_file_6 = ""
    cre_file_7 = ""
    continous_npc_script = ""
    continous_npc_name = ""
  BEGIN
    OUTER_TEXT_SPRINT portrait_lower ~%portrait%~
    ACTION_TO_LOWER portrait_lower

    ACTION_IF (STRING_LENGTH ~%source_dir%~ > 0) BEGIN
      COPY ~%MOD_FOLDER%/portraits/%source_dir%/%portrait%L.bmp~ ~override/%portrait%L.bmp~
      COPY ~%MOD_FOLDER%/portraits/%source_dir%/%portrait%M.bmp~ ~override/%portrait%M.bmp~
      COPY ~%MOD_FOLDER%/portraits/%source_dir%/%portrait_lower%r.bmp~ ~override/%portrait_lower%r.bmp~
    END

    ACTION_FOR_EACH cre_file IN ~%cre_file_1%~ ~%cre_file_2%~ ~%cre_file_3%~ ~%cre_file_4%~ ~%cre_file_5%~ ~%cre_file_6%~ ~%cre_file_7%~ BEGIN
      ACTION_IF (STRING_LENGTH ~%cre_file%~ > 0) AND FILE_EXISTS_IN_GAME ~%cre_file%~ BEGIN
        COPY_EXISTING ~%cre_file%~ ~override~
          WRITE_ASCIIE 0x34 ~%portrait%M~ #8
          WRITE_ASCIIE 0x3c ~%portrait%L~ #8
          BUT_ONLY_IF_IT_CHANGES
      END
    END

    ACTION_IF (STRING_LENGTH ~%continous_npc_script%~ > 0) BEGIN
      OUTER_TEXT_SPRINT npc_name_lower ~%continous_npc_name%~
      ACTION_TO_LOWER npc_name_lower
      OUTER_TEXT_SPRINT global_var ~bg2_%npc_name_lower%_portrait~
      OUTER_TEXT_SPRINT continuous_portrait_spell ~%portrait%P~

      ACTION_IF FILE_EXISTS_IN_GAME ~%continous_npc_script%.BCS~ BEGIN
        COPY ~%MOD_FOLDER%/spells/a7_pxxx.spl~ ~override/%continuous_portrait_spell%.spl~
          LPF ALTER_SPELL_EFFECT_RESREF
            INT_VAR match_opcode = 107 parameter2 = 0
            STR_VAR match_resource = ~A7PORTM~ resource = EVAL ~%portrait%M~
          END
          LPF ALTER_SPELL_EFFECT_RESREF
            INT_VAR match_opcode = 107 parameter2 = 1
            STR_VAR match_resource = ~A7PORTL~ resource = EVAL ~%portrait%L~
          END

        EXTEND_TOP ~%continous_npc_script%.BCS~ ~%MOD_FOLDER%/scripts/continuous_npc_portrait.baf~ EVAL
      END
    END
  END

// Removes a line of text from the current file
DEFINE_PATCH_FUNCTION REMOVE_TEXT_LINE
INT_VAR
  line = 0
STR_VAR
  search = ~~
RET
  line  // line number (-1 if no line is removed)
BEGIN
  SET line = "-1"
  SET ofs = 0
  FOR (i = 0; i >= 0 && ofs >= 0; ++i) BEGIN
    SET ofs2 = INDEX_BUFFER(~[%WNL%]~ ofs)
    SET ofs2 = (ofs2 < 0) ? INDEX_BUFFER(~$~ ofs) : ofs2
    PATCH_IF (ofs2 >= ofs) BEGIN
      READ_ASCII ofs text (ofs2 - ofs)
      PATCH_IF (i >= line) BEGIN
        PATCH_IF (~%text%~ STRING_CONTAINS_REGEXP ~%search%~ = 0) BEGIN
          SET ofs3 = INDEX_BUFFER(~[^%WNL%]~ ofs2)
          SET ofs2 = (ofs3 < 0) ? INDEX_BUFFER(~$~ ofs2) : ofs3
          PATCH_IF (ofs2 >= ofs) BEGIN
            DELETE_BYTES ofs (ofs2 - ofs)
            SET line = i
          END
          SET i = "-2"
        END ELSE BEGIN
          SET ofs = INDEX_BUFFER(~[^%WNL%]~ ofs2)
          SET ofs = (ofs <= ofs2) ? "-1" : ofs
        END
      END ELSE BEGIN
        SET ofs = INDEX_BUFFER(~[^%WNL%]~ ofs2)
        SET ofs = (ofs <= ofs2) ? "-1" : ofs
      END
    END ELSE BEGIN
      SET ofs = "-1"
    END
  END
END
