ACTION_IF (GAME_IS ~eet~) BEGIN
  INCLUDE ~%MOD_FOLDER%/lib/npc_functions.tph~

  // Baeloth ---
  OUTER_TEXT_SPRINT a7_portrait_change ~a7_pblt~
  COPY ~%MOD_FOLDER%/spells/a7_pxxx.spl~ ~override/%a7_portrait_change%.spl~
    LPF ALTER_SPELL_EFFECT_RESREF
      INT_VAR match_opcode = 107
      STR_VAR match_resource = ~A7PORTM~ resource = ~A7_BLTHM~
    END

    LPF ALTER_SPELL_EFFECT_RESREF
      INT_VAR match_opcode = 107
      STR_VAR match_resource = ~A7PORTL~ resource = ~A7_BLTHL~
    END

  ACTION_FOR_EACH script IN ~baeloth~ ~bdbaelot~ BEGIN
    ACTION_IF (FILE_EXISTS_IN_GAME ~%script%.bcs~) BEGIN
      EXTEND_TOP ~%script%.bcs~ ~%MOD_FOLDER%/scripts/portrait_change.baf~ EVAL
    END
  END

  // Dorn ---
  OUTER_TEXT_SPRINT a7_portrait_change ~a7_pdrn~
  COPY ~%MOD_FOLDER%/spells/a7_pxxx.spl~ ~override/%a7_portrait_change%.spl~
    LPF ALTER_SPELL_EFFECT_RESREF
      INT_VAR match_opcode = 107
      STR_VAR match_resource = ~A7PORTM~ resource = ~NDORNM~
    END
    LPF ALTER_SPELL_EFFECT_RESREF
      INT_VAR match_opcode = 107
      STR_VAR match_resource = ~A7PORTL~ resource = ~NDORNL~
    END

  ACTION_FOR_EACH script IN ~dorn_~ ~dorn~ ~dorn25~ BEGIN
    ACTION_IF (FILE_EXISTS_IN_GAME ~%script%.bcs~) BEGIN
      EXTEND_TOP ~%script%.bcs~ ~%MOD_FOLDER%/scripts/portrait_change.baf~ EVAL
    END
  END

  LAF UPDATE_EPILOG_PORTRAIT
  STR_VAR
    match_portrait = ~DORN.*~
    portrait = ~NDORNL~
  END


  // Neera ---
  OUTER_TEXT_SPRINT a7_portrait_change ~a7_pner~
  COPY ~%MOD_FOLDER%/spells/a7_pxxx.spl~ ~override/%a7_portrait_change%.spl~
    LPF ALTER_SPELL_EFFECT_RESREF
      INT_VAR match_opcode = 107
      STR_VAR match_resource = ~A7PORTM~ resource = ~NNEERAM~
    END
    LPF ALTER_SPELL_EFFECT_RESREF
      INT_VAR match_opcode = 107
      STR_VAR match_resource = ~A7PORTL~ resource = ~NNEERAL~
    END

  ACTION_FOR_EACH script IN ~neera_~ ~neera~ ~neer25~ BEGIN
    ACTION_IF (FILE_EXISTS_IN_GAME ~%script%.bcs~) BEGIN
      EXTEND_TOP ~%script%.bcs~ ~%MOD_FOLDER%/scripts/portrait_change.baf~ EVAL
    END
  END

  LAF UPDATE_EPILOG_PORTRAIT
  STR_VAR
    match_portrait = ~NEERA.*~
    portrait = ~NNEERAL~
  END

  // Rasaad ---
  OUTER_TEXT_SPRINT a7_portrait_change ~a7_prsd~
  COPY ~%MOD_FOLDER%/spells/a7_pxxx.spl~ ~override/%a7_portrait_change%.spl~
    LPF ALTER_SPELL_EFFECT_RESREF
      INT_VAR match_opcode = 107
      STR_VAR match_resource = ~A7PORTM~ resource = ~NRASAADM~
    END
    LPF ALTER_SPELL_EFFECT_RESREF
      INT_VAR match_opcode = 107
      STR_VAR match_resource = ~A7PORTL~ resource = ~NRASAADL~
    END

  ACTION_FOR_EACH script IN ~rasaad_~ ~rasaad~ ~rasa25~ BEGIN
    ACTION_IF (FILE_EXISTS_IN_GAME ~%script%.bcs~) BEGIN
      EXTEND_TOP ~%script%.bcs~ ~%MOD_FOLDER%/scripts/portrait_change.baf~ EVAL
    END
  END

  LAF UPDATE_EPILOG_PORTRAIT
  STR_VAR
    match_portrait = ~RASAAD.*~
    portrait = ~NRASAADL~
  END
END

ACTION_IF (GAME_IS ~bg2ee~) BEGIN
  ACTION_IF (NOT GAME_IS ~eet~) BEGIN
    COPY ~%MOD_FOLDER%/portraits/party_bg2/NBAELOTL.bmp~ ~override/BAELOTHL.bmp~
    COPY ~%MOD_FOLDER%/portraits/party_bg2/NBAELOTM.bmp~ ~override/BAELOTHM.bmp~
    COPY ~%MOD_FOLDER%/portraits/party_bg2/nbaelotr.bmp~ ~override/baelothr.bmp~

    COPY ~%MOD_FOLDER%/portraits/party_bg2/NDORNL.bmp~ ~override/DORNL.bmp~
    COPY ~%MOD_FOLDER%/portraits/party_bg2/NDORNM.bmp~ ~override/DORNM.bmp~
    COPY ~%MOD_FOLDER%/portraits/party_bg2/ndornr.bmp~ ~override/dornr.bmp~

    COPY ~%MOD_FOLDER%/portraits/party_bg2/NNEERAL.bmp~ ~override/NEERAL.bmp~
    COPY ~%MOD_FOLDER%/portraits/party_bg2/NNEERAM.bmp~ ~override/NEERAM.bmp~
    COPY ~%MOD_FOLDER%/portraits/party_bg2/nneerar.bmp~ ~override/neerar.bmp~

    COPY ~%MOD_FOLDER%/portraits/party_bg2/NRASAADL.bmp~ ~override/RASAADL.bmp~
    COPY ~%MOD_FOLDER%/portraits/party_bg2/NRASAADM.bmp~ ~override/RASAADM.bmp~
    COPY ~%MOD_FOLDER%/portraits/party_bg2/nrasaadr.bmp~ ~override/rasaadr.bmp~
  END
END
