# Never copy this from other mod, always use https://github.com/ALIENQuake/ProjectInfinity/wiki/Adding-metadata-for-mod
# Filename must be the same as tp2 basename, placed at the same folder where
# .tp2 file is located, use UTF8 (without BOM) encoding, everything is optional

# ini section header is required to avoid false detection
[Metadata]

# Author name or nick, don't use email address
Author = shaigan

# Full name of the mod, without the version number
Name = BG1 Style Portraits

# Short description of the mod, main goals, features etc
Description = BG1-style portraits for BG:EE, BG2:EE and EET. Enhanced NPC portraits, an extended Isandir custom portrait pack, and an optional component that removes NPC portraits from the player portrait picker.

# if you use GitHub.com, simply use https://github.com/AccountOrOrgName/RepositoryName
# read more about Delta Updates https://github.com/ALIENQuake/ProjectInfinity/wiki/Delta-Updates-for-mods-hosted-at-Github
Download = https://github.com/panshaigan/BG1-Style-Portraits

# Type of LABELs used by the mod, read more here https://www.gibberlings3.net/forums/topic/32516-tutorial-what-is-label
LabelType = GloballyUnique

# Dynamic Install Order, use mod ID as tp2 name without file extension and `setup-` prefix

# This mod must be installed *before* those ModID listed below, comma-separated list:
Before =

# This mod must be installed *after* those ModID listed below, comma-separated list:
After =
